name: Integration Pipeline

on:
  pull_request:
    types: [closed]

jobs:
  integration:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'integrations')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install markdown
          pip install requests
    
      - name: Run script
        run: python script.py
